# Generated by Django 4.0.1 on 2022-01-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('kind', models.SmallIntegerField(choices=[(1, 'Asset'), (2, 'Liability'), (3, 'Equity')])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_details', to='ledger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('kind', models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Array'), (3, 'Choice'), (4, 'Date')])),
                ('metadata', models.TextField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedAttributeDetailThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.userdefinedattribute')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.detail')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ledger.transaction'),
        ),
        migrations.AddConstraint(
            model_name='userdefinedattributedetailthrough',
            constraint=models.UniqueConstraint(fields=('detail', 'attribute'), name='detail_attribute_unique_together'),
        ),
    ]
