# Generated by Django 4.0.1 on 2022-01-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
        migrations.CreateModel(
            name='QuickCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_from_charge_kind', models.SmallIntegerField(choices=[(-1, 'Credit'), (1, 'Debit')])),
                ('account_to_charge_kind', models.SmallIntegerField(choices=[(-1, 'Credit'), (1, 'Debit')])),
                ('name', models.TextField()),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_quick_charges', to='ledger.account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_quick_charges', to='ledger.account')),
            ],
        ),
    ]
