# Generated by Django 4.0.1 on 2022-01-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_account_parent_quickcharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickCharge',
            new_name='QuickTransaction',
        ),
    ]
