# Generated by Django 4.0.1 on 2022-01-25 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename_quickcharge_quicktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detail',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quicktransaction',
            name='account_from_charge_kind',
            field=models.SmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit')]),
        ),
        migrations.AlterField(
            model_name='quicktransaction',
            name='account_to_charge_kind',
            field=models.SmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit')]),
        ),
    ]
