# Generated by Django 4.0.1 on 2022-01-25 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_account_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
