# Generated by Django 4.0.1 on 2022-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_account_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='is_leaf',
            field=models.BooleanField(default=False),
        ),
    ]
