# Generated by Django 4.0.3 on 2022-04-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
