# Generated by Django 4.0.3 on 2022-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_remove_recurringtransaction_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
