# Generated by Django 4.0.3 on 2022-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_recurringtransaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('key', 'company'), name='account_key_unique_for_company'),
        ),
    ]
